### ISSUE TITLE
move some dependencies to devdependencies

### ISSUE THREAD

**Issue by huineng** [IBM/node-sdk-core#266]
Although this is not a big deal , there are a few packages currently reported as dependency, that rather should be dev dependencies as they are mostly used during build phase and not at run time

``` 
"dependencies": {
    "@types/debug": "^4.1.12",
    "@types/file-type": "~5.2.1",
    "@types/isstream": "^0.1.0",
    "@types/node": "~10.14.19",
    "@types/tough-cookie": "^4.0.0",
    "expect": "^26.1.0"
  },
```

thanks

**Comment by dpopp07** [comment]
Thanks for the issue @huineng 

`expect` should not be included here because it [is part of the exposed API](https://github.com/IBM/node-sdk-core/blob/main/lib/sdk-test-helpers.ts) that provides helpers for unit tests of depending SDKs.

For the others, we'll look at moving them.

**Comment by mpawlow** [comment]
@dpopp07 
- `Question`: Is there any update on removing **expect** from the runtime **dependencies**?
- `Problem`: Our Security tools are picking up and flagging **expect** with a vulnerability (see details below) that needs to be remediated
- Assumption: **devDependencies** are excluded from the OSS scans

```
  `-- @ibm-cloud/cloudant@0.9.1
    `-- ibm-cloud-sdk-core@4.3.0
      `-- expect@27.5.1
        `-- jest-message-util@27.5.1
          `-- micromatch@4.0.5
```

### [PSIRT][PVR0511742] micromatch-4.0.5.tgz (Publicly disclosed vulnerability found by Mend)

Filename: micromatch-4.0.5.tgz
Artifact ID: micromatch-4.0.5.tgz
Group ID: micromatch
Name: micromatch
Version: 4.0.5
Description: Glob matching for javascript/node.js. A replacement and faster alternative to minimatch and multimatch.
Type: NODE_PACKAGED_MODULE

Mend References (at the time of ADV creation):
https://www.mend.io/vulnerability-database/CVE-2024-4067
https://nvd.nist.gov/vuln/detail/CVE-2024-4067

**CVE Details**

CVEID: [CVE-2024-4067](https://nvd.nist.gov/vuln/detail/CVE-2024-4067)
Description: Node.js micromatch module is vulnerable to a denial of service; caused by a regular expression denial of service (ReDoS) flaw in micromatch.braces() in index.js. By sending a specially crafted payload; a remote attacker could exploit this vulnerability to increase the consumption time until the application hangs or slows down.
CVSS Base Score: 7.5
CVSS Temporal Score: https://exchange.xforce.ibmcloud.com/vulnerabilities/290676 for more information
CVSS Vector: (CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H)

**Comment by ricellis** [comment]
@dpopp07 I think it would be better to encourage the downstream SDKs to pick up test dependencies like `expect` through their own `devDependencies` block (i.e. add it to the template repo) rather than including them as dependencies of the core. I guess that might be a breaking change, but it would seem to be a lot cleaner than pulling in a bunch of test dependencies for all the SDK installs.

Whilst it would likely be cleaner to package the test helpers separately as proposed in #174 I think it is possible and potentially less disruptove (at least as a first step) to continue to package them with the core. I think this is possible with the dependencies "missing" since they are only referenced by the test code. As such the code paths that need those deps are never used at runtime. It would only cause build/test time problems for downstream SDKs that didn't update their devDependencies to include `expect` (and friends?).

FWIW I tried this out locally with our SDK and a modified core that has `expect` as a `devDependency`. The generated tests ran fine even without me adding `expect` to our `devDependencies` because it is also inlcuded by `jest` (which is already in the SDK template anyway).

**Comment by dpopp07** [comment]
@ricellis thanks for the comment - that is some valuable insight. Sounds like we might be able to get away with removing this production level dependency without a breaking change due to the nature of the development dependencies in the template, etc.

I'll be investigating that soon.
