### ISSUE TITLE
Upgrade retry-axios which depend on a vulnerable  axios version (1.6.8) for 5.0.1 release version

### ISSUE THREAD

**Issue by 0zymandia5** [IBM/node-sdk-core#284]
due an open vulnerailtity [CVE-2024-39338]  on axios vulnerable version

### When reporting a bug, please be sure to include the following:
- [ ] Steps to reproduce:
```
warlock:repo_namel$ npm ls axios
repo_anme@0.0.1 /2/Repo/
└─┬ ibm-cloud-sdk-core@5.0.1
  ├── axios@1.7.4
  └─┬ retry-axios@2.6.0
    └── axios@1.6.8
```
- [ ] Node version : 18.X
- [ ] SDK version: 5.0.1

**Comment by dpopp07** [comment]
Hmm the `retry-axios` package [doesn't specify any version of `axios`](https://github.com/JustinBeckwith/retry-axios/blob/v2.6.0/package.json#L38). It should be pulling in the latest. The newest versions of that package don't change how they pull in `axios`.

**Comment by 0zymandia5** [comment]
Yes I noticed, should I open a Issue for them?

**Comment by dpopp07** [comment]
If the latest version of `axios` isn't being populated like it should, maybe. I don't know if us updating our version would make a difference, since their `package.json` is the same in all versions. But I'm not sure what they'll be able to do about either. It's odd that it isn't already pulling in the latest.

Is version 1.6.8 referenced in your package lock file?

**Comment by dpopp07** [comment]
This is what I see for the Node core package:
```
[node-sdk-core] $ npm list axios
ibm-cloud-sdk-core@5.0.1 /Users/dustinpopp/dev/node-sdk-core
├── axios@1.7.4
└─┬ retry-axios@2.6.0
  └── axios@1.7.4 deduped
```

**Comment by 0zymandia5** [comment]
You are correct,  doing 
` npm dedupe`
Solve the dependency on the package-lock.
